name: tests

on:
  push:
  pull_request:
    branches:
      - $default-branch

jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: x64
      - run: pip install -r requirements_test.txt
      - run: python setup.py bdist_wheel sdist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
